name: grafanaimagerenderer_ci

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - master
  schedule:
    - cron: '0 1 * * 6'

jobs:
  main:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: hferreira/grafana-image-renderer:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
